# Generated by Django 3.2.9 on 2022-01-16 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='participants',
        ),
        migrations.AddField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default=True, verbose_name='is active?'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='ExperienceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='experience date')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='experiences.experience')),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experience record',
                'verbose_name_plural': 'experiences record',
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='image url')),
                ('periodic_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='experiences.experience')),
            ],
            options={
                'verbose_name': 'experience image',
                'verbose_name_plural': 'experience images',
            },
        ),
        migrations.CreateModel(
            name='ExperienceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], verbose_name='week day')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_days', to='experiences.experience')),
            ],
        ),
    ]
