# Generated by Django 3.2.9 on 2022-01-16 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20220116_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceimage',
            old_name='periodic_experience',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='hours duration'),
        ),
        migrations.AddField(
            model_name='experience',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 16, 18, 8, 39, 898250, tzinfo=utc), verbose_name='time'),
        ),
    ]
