# Generated by Django 3.2.9 on 2022-01-18 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiences', '0003_auto_20220116_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateTimeField(verbose_name='experience date')),
            ],
            options={
                'verbose_name': 'experience ticket',
                'verbose_name_plural': 'experience tickets',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], verbose_name='week day')),
                ('time', models.TimeField(verbose_name='time')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.RemoveField(
            model_name='experiencerecord',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='experiencerecord',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='time',
        ),
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='one time date'),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True, verbose_name='periodic start date'),
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.IntegerField(choices=[(1, 'one day'), (2, 'periodic')], default=1, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='ExperienceCalendar',
        ),
        migrations.DeleteModel(
            name='ExperienceRecord',
        ),
        migrations.AddField(
            model_name='schedule',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='experienceticket',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='experienceticket',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
