# Generated by Django 3.2.9 on 2022-01-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_guide_plan_expire_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiences', '0006_auto_20220118_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(default='', verbose_name='comment')),
                ('rating', models.IntegerField(default=5, verbose_name='rating')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_guides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guide reviews',
            },
        ),
        migrations.CreateModel(
            name='ExperienceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(default='', verbose_name='comment')),
                ('rating', models.IntegerField(default=5, verbose_name='rating')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='experiences.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experience reviews',
            },
        ),
    ]
