# Generated by Django 3.2.9 on 2022-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_experiencereview_guidereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencereview',
            name='comment',
            field=models.CharField(default='', max_length=300, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='comment',
            field=models.CharField(default='', max_length=300, verbose_name='comment'),
        ),
    ]
