# Generated by Django 3.2.9 on 2022-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_auto_20220119_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(db_index=True, default='', max_length=254, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='url',
            field=models.URLField(default='https://i.imgur.com/ExjELDm.jpg', verbose_name='image url'),
        ),
    ]
