# Generated by Django 3.2.9 on 2022-01-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_auto_20220121_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='one time date'),
        ),
    ]
