# Generated by Django 3.2.9 on 2022-01-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0010_alter_experience_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='keywords',
            field=models.TextField(null=True, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='periodic start date'),
        ),
    ]
