# Generated by Django 3.2.9 on 2022-01-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_guide_plan_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_pic',
            field=models.URLField(default='', verbose_name='header pic'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='', verbose_name='profile pic'),
        ),
    ]
