# Generated by Django 3.2.9 on 2021-12-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='designation')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('duration', models.IntegerField(choices=[(1, 'Monthly'), (2, 'Semesterly'), (3, 'Anually')], verbose_name='duration')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
            },
        ),
    ]
