# Generated by Django 3.2.9 on 2022-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20211229_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="slug",
            field=models.SlugField(
                default=None, unique=True, verbose_name="subscription slug"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="designation",
            field=models.CharField(max_length=128, verbose_name="designation"),
        ),
    ]
