# Generated by Django 3.2.9 on 2022-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20220115_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='comment'),
        ),
    ]
